yolov7_aadhar_model_path : models/aadhar.pt

yolov7_pan_model_path : models/pan.pt

yolov7_cheque_model_path : models/cheque.pt

tocr_model : microsoft/trocr-small-printed

vit_transformer_path : google/vit-base-patch16-224

vit_transformer_model : models/classify.pth
