yolov7_aadhar_model_path : src/documentExtractorAPI/models/aadhar.pt

yolov7_pan_model_path : src/documentExtractorAPI/models/pan.pt

yolov7_cheque_model_path : src/documentExtractorAPI/models/cheque.pt

tocr_model : microsoft/trocr-small-printed

vit_transformer_path : google/vit-base-patch16-224

vit_transformer_model : src/documentExtractorAPI/models/classify.pth
